### ISSUE TITLE
Standardize README pages for all repos.

### ISSUE THREAD

**Issue by karthik** [ropensci-archive/ropensciToolkit#1]

**Comment by sckott** [comment]
@karthik  What do you have in mind

**Comment by karthik** [comment]
I should close this ticket. We already have a footer at the end of each repo. That's the start that I had in mind. Might be useful to have a similar structure for everything too. e.g.

Installation
Getting started
use cases
More resources
...

**Comment by sckott** [comment]
Okay, will have a look and update those that are lacking
